version: '3.8'

services:
    database_service:
                    image: mysql:latest
                    restart: always
                    environment:
                        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                        MYSQL_DATABASE: ${MYSQL_DATABASE}
                        MYSQL_USER: ${MYSQL_USER}
                        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                        MYSQL_AUTHENTICATION_PLUGIN: ${MYSQL_AUTHENTICATION_PLUGIN}
                    ports:
                      - "3306:3306"
                    env_file:
                      - .env
                    volumes:
                      - mysql_data:/var/lib/mysql
                      - ./Users.sql:/docker-entrypoint-initdb.d/Users.sql
    server_service:
                  build:
                       context: .
                       dockerfile: Dockerfile
                  ports:
                    - "8080:8080"

volumes:
  mysql_data: