version: '3.8'

services:
  database_service_test:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: Users_database_test
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_AUTHENTICATION_PLUGIN: ${MYSQL_AUTHENTICATION_PLUGIN}
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./Users.sql:/docker-entrypoint-initdb.d/Users.sql
    networks:
      - backend_network_test
  server_service_test:
    build:
      context: .
      dockerfile: Dockerfile-test
    ports:
      - "8080:8080"
    depends_on:
      - database_service_test
    networks:
      - backend_network_test

networks:
  backend_network_test:
    driver: bridge
