# Dockerfile for creating server testing image
FROM ubuntu:latest
LABEL authors="gszp1"

RUN apt-get update -y && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y maven

RUN mkdir -p server_tests
COPY pom.xml ./server_tests
COPY src ./server_tests/src
WORKDIR /server_tests

RUN find ./src/main/java -type d -name "client" -exec rm -r {} +

EXPOSE 8080

CMD ["mvn", "test"]